name: Wokwi Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 1. Build Firmware ESP32 menggunakan Arduino CLI
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 Core & Libraries
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
          arduino-cli lib install "DHT sensor library"
          arduino-cli lib install "Adafruit Unified Sensor"

      - name: Compile ESP32 Sketch
        run: |
          mkdir -p build
          arduino-cli compile --fqbn esp32:esp32:esp32 --output-dir build ./main

      # 2. Jalankan Simulasi Wokwi CI
      - name: Run Wokwi Simulation Test
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: .
          timeout: 30000
          expect_text: '{"distance"'
